[package]
name = "tetris-cl"
version = "0.1.0"
authors = ["nnyx7 <nnyx77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.14"
termion = "1.5"
rand = "0.7"
